name: Garage
description: Lightweight S3-compatible object storage
category: storage
docs: https://garagehq.deuxfleurs.fr/documentation/quick-start/

services:
  garage:
    image: dxflrs/garage:v2.3.0
    port: 3900
    icon: amazons3
    environment:
      GARAGE_DEFAULT_ACCESS_KEY:
        generated: password
      GARAGE_DEFAULT_SECRET_KEY:
        generated: password
      GARAGE_DEFAULT_BUCKET: default-bucket
      AWS_ACCESS_KEY_ID: ${garage.GARAGE_DEFAULT_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${garage.GARAGE_DEFAULT_SECRET_KEY}
      AWS_DEFAULT_REGION: garage
      S3_ENDPOINT: http://garage:3900
      S3_BUCKET: default-bucket
      S3_REGION: garage
      S3_ACCESS_KEY_ID: ${garage.GARAGE_DEFAULT_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${garage.GARAGE_DEFAULT_SECRET_KEY}
      S3_FORCE_PATH_STYLE: "true"
    volumes:
      - meta:/var/lib/garage/meta
      - data:/var/lib/garage/data
