name: lightform-example-basic

ssh:
  username: lightform

apps:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      env:  # Make environment variables available during build
        - EXAMPLE_VAR
    server: 157.180.47.213
    environment:
      plain:
        - EXAMPLE_VAR=test
      secret:
        - SECRET_VAR
        - POSTGRES_PASSWORD
    proxy:
      app_port: 3000
    health_check:
      path: /api/health

services:
  db:
    image: postgres:17
    server: 157.180.47.213
    ports:
      - "5433:5432"
    environment:
      plain:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
