name: gmail

ssh:
  username: luma

docker:
  username: elitan

apps:
  web:
    image: elitan/luma-test-web
    servers:
      - 157.180.25.101
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    environment:
      plain:
        - EXAMPLE_VAR=test
      secret:
        - SECRET_VAR
    proxy:
      hosts:
        - test.eliasson.me
      app_port: 3000
    health_check:
      path: /api/health

services:
  db:
    image: postgres:17
    servers:
      - 157.180.25.101
    ports:
      - "5433:5432"
    environment:
      plain:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
