name: gmail

ssh:
  username: luma

apps:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    servers:
      - 157.180.25.101
    environment:
      plain:
        - EXAMPLE_VAR=test
      secret:
        - SECRET_VAR
        - POSTGRES_PASSWORD
    proxy:
      hosts:
        - test2.eliasson.me
      app_port: 3000
    health_check:
      path: /api/health

services:
  db:
    image: postgres:17
    servers:
      - 157.180.25.101
    ports:
      - "5433:5432"
    environment:
      plain:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
