name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-proxy:
    name: Test Go Proxy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('packages/proxy/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        working-directory: ./packages/proxy
        run: go mod download

      - name: Run Go tests
        working-directory: ./packages/proxy
        run: go test -v ./...

      - name: Run Go tests with race detection
        working-directory: ./packages/proxy
        run: go test -v -race ./...

  test-cli:
    name: Test Bun CLI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            packages/cli/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('packages/cli/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun dependencies
        working-directory: ./packages/cli
        run: bun install

      - name: Run Bun tests
        working-directory: ./packages/cli
        run: bun test

      - name: Build CLI
        working-directory: ./packages/cli
        run: bun run build

      - name: Test CLI binary
        run: |
          if [ -f "packages/cli/dist/index.js" ]; then
            echo "CLI built successfully"
            node packages/cli/dist/index.js --help || echo "CLI help command executed"
          else
            echo "Build failed - packages/cli/dist/index.js not found"
            exit 1
          fi

  test-matrix:
    name: Cross-platform tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Go dependencies
        working-directory: ./packages/proxy
        run: go mod download

      - name: Install Bun dependencies
        working-directory: ./packages/cli
        run: bun install

      - name: Test Go proxy (basic)
        working-directory: ./packages/proxy
        run: go test ./...

      - name: Test Bun CLI
        working-directory: ./packages/cli
        run: bun test
